name: flutter_mobilepay_payment
description: A Flutter plugin for integrating Scandinavian payment provider MobilePay.
version: 0.0.1
author: Kristoffer Vinther <kristoffer@zliide.com>
homepage: https://github.com/zliide/flutter_mobilepay_payment

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: io.flutter.fluttermobilepaypayment
    pluginClass: FlutterMobilepayPaymentPlugin

environment:
  sdk: ">=1.19.0 <2.0.0"
