name: flutter_mobilepay_payment
description: A Flutter plugin for integrating Scandinavian payment provider MobilePay.
version: 0.3.0
author: Kristoffer Vinther <kristoffer@zliide.com>
homepage: https://github.com/zliide/flutter_mobilepay_payment

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.zliide.flutter_mobilepay_payment
        pluginClass: FlutterMobilepayPaymentPlugin
      ios:
        pluginClass: FlutterMobilepayPaymentPlugin
